/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MemoryIndexImport } from './routes/memory/index'
import { Route as MemoryUsersImport } from './routes/memory/users'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MemoryIndexRoute = MemoryIndexImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => rootRoute,
} as any)

const MemoryUsersRoute = MemoryUsersImport.update({
  id: '/memory/users',
  path: '/memory/users',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/memory/users': {
      id: '/memory/users'
      path: '/memory/users'
      fullPath: '/memory/users'
      preLoaderRoute: typeof MemoryUsersImport
      parentRoute: typeof rootRoute
    }
    '/memory/': {
      id: '/memory/'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memory/users': typeof MemoryUsersRoute
  '/memory': typeof MemoryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memory/users': typeof MemoryUsersRoute
  '/memory': typeof MemoryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/memory/users': typeof MemoryUsersRoute
  '/memory/': typeof MemoryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/memory/users' | '/memory'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/memory/users' | '/memory'
  id: '__root__' | '/' | '/memory/users' | '/memory/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemoryUsersRoute: typeof MemoryUsersRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemoryUsersRoute: MemoryUsersRoute,
  MemoryIndexRoute: MemoryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/memory/users",
        "/memory/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/memory/users": {
      "filePath": "memory/users.tsx"
    },
    "/memory/": {
      "filePath": "memory/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
